numactl/numactl

CHANGES, libnuma.c
=> once again

libnuma.c
This "shouldn't" happen, but can anyway in some scenarios (like if
syscall() is getting intercepted via LD_PRELOAD).  If it does occur,
it's nicer to not go into an infinite loop of memory allocations and
OOM the system.
=> Handle sched_getaffinity() failing with errno != EINVAL.

numa.3
I believe that the usage of "further more" should really be "futhermore". I'm not sure that "further more" makes sense in this context.
=> "Further more" should be a single word

test/distance.c
Patch fixes distance test for numa nodes which are non contiguous.
=> Fix: numactl distance between sparse nodes

memhog.8
Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
=> memhog: add man page

Makefile.am
Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
=> Added memhog.8 to Makefile.am

memhog.c
Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
=> Synchronized usage function with man page

memhog.c
Solves issue #50
Signed-off-by: Sanskriti sharma <sansharm@redhat.com>
=> Removed unnecessary exit from memhog.c

.packit.yaml, numactl.spec
Let us introduce [packit service](https://packit.dev) to you - the automation to integrate upstream open source projects into Fedora operating system.
After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.
But there is more. By using packit, you can for example enable adding new releases into Fedora Rawhide.
What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!
For more info, please:
* check out the documentation: https://packit.dev/docs/
* contact @packit-service
The spec you see in …
=> Enable copr builds and add packit config

numactl.c, numademo.c
These are some minor fixes/improvements I made in preparation for a larger series which isn't yet ready for a PR.
=> Minor fixes

util.h
=> Do not stringify SYMVER symbols

syscall.c
=> add loongarch support

clearcache.c, libnuma.c, memhog.c, migratepages.c, migspeed.c, numactl.c, numademo.c, numamon.c, numastat.c, shm.c, stream_lib.c, stream_main.c, syscall.c, test/migrate_pages.c, test/move_pages.c, test/node-parse.c, test/prefered.c, test/tbitmap.c, util.c, util.h
1-4th commit to cleanup code simply.
5th commit  fix memory and file handle leak in shm.c
6-8th commit fix memhog issue.
My work focuses on kernel memory management, I was interested in this package.
can I be  a maintainer of this repository?
=> Modify the code to make it look cleancode and fix some issues

libnuma.c
fix the memory leak of numa_preferred api
#138
=> fix the memory leak of numa_preferred api

libnuma.c
=> libnuma: clear errno at the end of numa_init

libnuma.c
#145 
refactor the method for obtaining nodemask_sz.
=> fix wrong nodemask_sz when CONFIG_NODES_SHIFT is less than 5

.github/workflows/codeql.yml, .github/workflows/cut-release.yml, .github/workflows/makefile.yml
Resolves https://github.com/numactl/numactl/issues/166
=> Add minimum workflow permissions

numactl.c
=> fix: fix memory leaks when run with -H

libnuma.c
=> Fix issue #190 about numa_exit_on_warn does not work

numactl.8, numactl.c
Since --weighted-interleave/-w option was added to numactl at b67fb88, we should add the description to help message and man page.
=> numactl: Add documentation for weighted interleave

numactl.c
#224 reports issues with alignment of columns for node distances.  This patch increases the field width for the table.
=> Increase field width for node distances to help readability on larger nodes
