numactl/numactl

syscall.c

The way __GLIBC_PREREQ() is currently used means that it's evaluated
even if __GLIBC__ is not defined. But obviously, __GLIBC_PREREQ will
not exist if __GLIBC__ is not defined, causing build failures on C
libraries not defining __GLIBC__ such as the musl C library.
Uclibc pretends to be glibc so we need to exclude it from the check.
Patch originally taken from:
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/numactl/patches/musl.patch
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
[Bernd: Added uClibc exclusion]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
[Thomas: improve patch description.]

Use __GLIBC_PREREQ only when __GLIBC__ is defined

---

syscall.c

The way __GLIBC_PREREQ() is currently used means that it's evaluated
even if __GLIBC__ is not defined. But obviously, __GLIBC_PREREQ will
not exist if __GLIBC__ is not defined, causing build failures on C
libraries not defining __GLIBC__ such as the musl C library.
The first try to fix the problem was wrong, sorry. This patch reverts https://github.com/numactl/numactl/commit/3770bdc4fa7b9059db5cd2aa8bb09b50fa15e456 and adds the proper fix.
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
[Bernd: Reworked to fix uClibc]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
[Thomas: improve patch description.]

Fix usage of __GLIBC_PREREQ for non-glibc toolchains

---

libnuma.c

It appends a colon and strerror(errno), so avoid newlines at the ends
of messages passed to it.  Also make sure errno is set to something
vaguely sensible before calling it if it's not right after a syscall,
so that we don't just report whatever status happened to be left over
from whatever set it last.

Clean up numa_error() calls.

---

libnuma.c

Implementation of this function was based on outdated assumption
that memory read causes page fault (and allocation of physical memory).
This assumption is not true for Linux since 2.6.32 (a13ea5b); Uninitialized
memory is backed by zero_page until time of first write.
This patch makes numa_policy_memory() works as expected, by rewriting
(instead of just reading) first byte of every page.

Fix for numa_police_memory()

---

test/regress

As some of numa-nodes might be named 0,8 grep of few information from numactl command fails with invalid node 1. This patch fixes this issue by introducing list and necessary changes to grep
appropriately for each numa node.

Fix regress test for invalid hard code of nodenames

---

test/distance.c

The previous static allocation does allow proper usage of array, this patch allocates dynamic array for number of nodes

Fix: allocation of dynamic array

---

numademo.c

Patch fixes numademo test for numa nodes which are non contiguous. This is tested on both machines with contiguous and sparse nodes.

Fix: numademo test between sparse nodes

---

syscall.c

While 32-bit ARM systems do not support NUMA, it is useful to be able
to build libnuma for these systems. Distributions would then not need to
special case ARM builds for software that uses libnuma when available.
libnuma's API requires users to check for NUMA support at runtime using
numa_available() which will just always return -1 on ARM.
https://bugs.debian.org/796802
https://launchpad.net/bugs/1711478
Original patches by Uwe Kleine-König <uwe+debian@kleine-koenig.org> and
Tiago Stürmer Daitx <tiago.daitx@ubuntu.com>.
Signed-off-by: dann frazier <dannf@ubuntu.com>

Allow building on ARM systems

---

numastat.8

The numastat manpage is missing a "NAME" section, which appears to be due
to a typo. This causes problems with commands like apropos and whatis.
Discovered by lintian(1):
https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html
Signed-off-by: dann frazier <dannf@ubuntu.com>

Add "NAME" section to numastat manpage

---

numademo.c

Patch adds check to avoid memory-less nodes while traversing till max node, and this also prevents nodes_to_use sysmalloc failure as nodes_to_use is malloc'ed with numa_num_configured_nodes which
returns the number of nodes configured with memory.

Fix: node_list with memory-less nodes

---

numademo.c

In few sparse node systems, test fails with invalid argument at set_mempolicy through numa_preferred_node. Patch fixes it by providing a valid wrong node.
Tested on both sparse and contiguous types of nodes.

numademo: fix wrong node input

---

test/distance.c

The previous implementation did not consider memory-less nodes as numa_num_configured_nodes() returns only nodes with memory and numa_node_size() check is unnecessary for distance check. Hence
removed the check for memory.

Fix: distance test to include all existing nodes

---

Makefile.am
test/move_pages.c

This was pointed out by @bjsprakash in #8.
After the bug is corrected, we can re-enable the test in `make check` and also Travis-CI.
@andikleen Please review.
Fixes #8

Correct calculation of nr_nodes and re-enable move_pages test

---

numastat.c

ShmemHugePages and ShmemPmdMapped were recently added to
/sys/devices/system/node/node*/meminfo. Adding entries for them in the
system_meminfo data structure got rid of the error "Token Node not in hash
table."
Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>

Fix: Add ShmemHugePages and ShmemPmdMapped to system_meminfo[]

---

numaif.h
test/randmap.c

`MPOL_LOCAL` has been a policy since Linux 3.8, but is missing from `numaif.h`.
- Add missing `MPOL_LOCAL` policy to `numaif.h`
- `MPOL_MAX` now matches the Linux kernel (should be one greater than any other policy)
This is a minor but breaking change for applications that have defined `MPOL_LOCAL` themselves without checking if already defined.
Fixes #38

Add missing MPOL_LOCAL policy in numaif.h

---

libnuma.c
numademo.c

Fixes valgrind warnings when running:
```
valgrind --leak-check=full --show-leak-kinds=all .libs/numademo -t -e 1M
```

Valgrind memory leak fixes

---

clearcache.c

Only level 1 distinguishes between data and intstruction cache

Correct sysconf constants

---

distance.c
syscall.c
test/bind_range

This patch enables building on Linux for s390x (aka Z aka Mainframe):
* ```syscall.c``` : Add syscalls ```__NR_mind->__NR_move_pages``` = 235-239
* ```distance.c``` : ```read_distance``` will return if there is no node directory in sysfs so this needs to be checked before trying to use this table in ```numa_distance()``` 
* ```test/bind_range``` : The format of ```/proc/cpuinfo``` is different for s390x so parsing the highest and lowest processor ids will not work as is
```
vendor_id       : IBM/S390
bogomips per cpu: 20325.00
max thread id   : 0
features	: esan3 zarch stfle msa ldisp eimm dfp etf3eh highgprs vx sie 
facilities      : 0 1 2 3 4 6 7 9 10 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 40 41 42 43 44 45 46 47 48 49 50 51 52 53 55 57 74 75 76 77 80 81 …
```

Enable building on s390x

---

numastat.c

This ease the result query by bash $?

numastat: when reading no-exist pid, return EXIT_FAILURE

---

test/checktopology

Some machine configurations with GPUs have nodes without cpu configured. This patch skips check for those nodes.

numatopology: Add check for cpu-less nodes

---

numastat.8

The man page gives no hint about whether memory usage information
relates to resident pages or virtual memory.  The answer may not be
obvious to the user, so explicitly mention that only resident pages are
counted.
Suggested-by: Daniele Palumbo <daniele@retaggio.net>
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>

numastat.8: clarify that information relates to resident pages

---

test/bind_range

Patch handles cpu-less nodes by selecting nodes with cpus to be used for binding
Ex.
node 8 cpus : 8 9 10 11
node 255 cpus:

Handle cpu-less node for bind_range test

---

LICENSE.GPL2
LICENSE.LGPL2.1
Makefile.am

Licensing information was already present in `README.md`:
- `numactl` and the demo programs are under the GNU General Public License, v.2.
- `libnuma` is under the GNU Lesser General Public License, v2.1.
However, we weren't shipping a copy of the license text, so let's retify that by including a copy of the text of both GPLv2 and LGPLv2.1.
Also update `Makefile.am` to include the `LICENSE.*` files in a dist tarball.
Fixes #68.

Add license files: GPLv2 + LGPLv2.1

---

test/move_pages.c

If hardware that doesn't support this test is not available, we should SKIP rather than FAIL.
This is akin to what we've done with `test/regress` in commit 4042d9e20f755f.

Skip `test/move_pages` if we don't have at least two nodes available

---

libnuma.c
numa.3
numa.h
versions.ldscript

numa_node_to_cpus() caches the cpu to node mapping, and not updates it
during the cpu online/offline event.
Ideally, in order to update the mapping automatically, it requires
something like udev to spy on kernel event socket, and update cache if
event happen. This solution is a little complicated inside a libnuma.so. In
stead of doing so, exposing an API numa_node_to_cpu_outdated() for user,
and saddling the event-detecting task to the user.
So the user of libnuma can work using either of the following models:
-1. blindless outdate cache if careless about performance
numa_node_to_cpu_outdated();
numa_node_to_cpu();
-2. event driven spy on kernel event, if happened, call
numa_node_to_cpu_outdated();

libnuma: introduce an API to outdate cpu to node mapping

---

test/move_pages.c

a7c4bc7 introduced a error about incompatible pointer types.
test/move_pages.c:35:39: error: passing argument 2 of
'numa_node_size' from incompatible pointer type
[-Werror=incompatible-pointer-types]
if (numa_node_size(a, &free_node_sizes) > 0)
^^
Unified variable type and fix it.
Signed-off-by: Hongzhi.Song <hongzhi.song@windriver.com>

numademo: fix incompatible pointer types

---

shm.c

Fix memory to be mapped read/write, so that the "touch" option can write to it.
Signed-off-by: Patrick Mansfield <patrick.mansfield@cpacketnetworks.com>

Fix crashes when using the "--touch" option.

---

shm.c

numa_police_memory() accesses the mapping region, which size is shmlen.
If the shared file can not be extended to shmlen, then SIGBUS will be
triggered. Instead exit() is more graceful.

shm: exit when ftruncate() fails

---

numactl.8

numactl man page has incorrect information about --localalloc option.
Current Text:-
--localalloc, -l
Always allocate on the current node.
It should be
--localalloc, -l
Try to allocate on the current node of the process, but if memory cannot be allocated there fall back to other nodes.
Signed-off-by: Seeteena Thoufeek <s1seetee@linux.vnet.ibm.com>

Update manpage description of --localalloc option

---

.travis.yml
configure.ac
libnuma.c
syscall.c
util.h

Originally proposed in https://src.fedoraproject.org/rpms/numactl/pull-request/3
Comment from Jeff Law:
> This package is currently opted out of LTO because it uses ASMs to implement symbol versioning. ASMs like this are fundamentally incompatible with LTO because GCC does not look inside the ASM string to find symbol references. Starting with gcc-10 there is a new symbol attribute for implementing symbol versioning. This patch changes numactl to use that symbol attribute and re-enables LTO. Note the patch includes a fallback to the old way of implementing symbol versioning via asms, so in theory it should work with clang as well as gcc-9 and earlier. I haven't fully tested the fallback path.

Use symver attribute not asms for symbol versioning.

---

Makefile.am
configure.ac

Pushing two more small commits related to LTO, follow ups for #92, then bumping the version on the `configure.ac` file.

Release numactl 2.0.14

---

test/bind_range

This patch filters out numa nodes with more than 0 MB memory so that those nodes can be used for cpunodebind tests
eg.
node 17 cpus: 120 121 122 123 124 125 126 127 128 129 130 131
node 17 size: 0 MB
node 17 free: 0 MB
Signed-off-by: Harish <harish@linux.ibm.com>

test/bind_range: Handle memory-less nodes for cpubind

---

numademo.c

Patch adds a check to skip numademo test in case minimum of two configurable nodes are not available for testing
Signed-off-by: Harish <harish@linux.ibm.com>

numademo: Skip if enough configurable nodes are not available

---

configure.ac

Fix is from https://github.com/spack/spack/pull/21894
This bug fixes failures to configure on a number of HPC platforms
```
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/WS2/blake14/spack/lib/spack/env/gcc/gcc accepts -g... (cached) yes
checking for /usr/WS2/blake14/spack/lib/spack/env/gcc/gcc option to accept ISO C89... (cached) none needed
checking whether /usr/WS2/blake14/spack/lib/spack/env/gcc/gcc understands -c and -o together... (cached) yes
checking dependency style of /usr/WS2/blake14/spack/lib/spack/env/gcc/gcc... (cached) gcc3
checking for thread local storage (TLS) class... _Thread_local
/g/g19/blake14/sand/numactl_fix/numactl/configure: line 12191: syntax error near unexpected token `fi' …
```

Bash needs a noop if TLS isn't found.

---

libnuma.c
numa.3
numa.h
numactl.8
numactl.c
numaif.h
versions.ldscript

In Linux kernel v5.12, a new mode flag MPOL_F_NUMA_BALANCING is added
to set_mempolicy() to optimize the page placement among the NUMA nodes
with the NUMA balancing mechanism even if the memory of the
applications are bound with MPOL_BIND.  For details about kernel
change, please refer to commit bda420b98505 ("numa balancing: migrate
on fault among multiple bound nodes").  This patch adds the
corresponding support to libnuma and numactl.
A new API: numa_set_membind_balancing() is added to libnuma.  It is
same as numa_set_membind() except that the Linux kernel NUMA balancing
will be enabled for the task if the feature is supported by the
kernel.
At the same time, a new option: --balancing (-b) is added to numactl.
Which can be used before the --membind/-m memory policy in the command
line. …

Support to optimize page placement via NUMA balancing among bound nodes

---

test/bind_range

Regex used in bind_range test that does not exclude the cpu-less node, fix it with appropriate regex.
Signed-off-by: Harish <harish@linux.ibm.com>

Fix: regex for bind_range test

---

numademo.c

Numademo test tries to use nodes 0 and 1 to set bitmask. This is affecting the systems which does not have such node numbering.
E.g: available: 4 nodes (4-7)
Instead use the first two nodes of the list.
Also use the counter i to determine every 8th node (FRACT_NODE) to run the regression tests replacing the node number.
Signed-off-by: Harish <harish@linux.ibm.com>

numademo: Use first two nodes instead of node 0 and 1

---

libnuma.c

When numa_police_memory() read-write to memory, it can risk the race of
another thread write to the same area.
Using atomic function to protect the read-write operation

libnuma: make numa_police_memory() free of race

---

Makefile.am
configure.ac
numa.pc.in

numactl unconditionally uses `__atomic_fetch_and` but some architectures (e.g. sparc) needs to link with -latomic to be able to use it. So check if -latomic is needed and update numa.pc accordingly
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

link with -latomic if needed

---

numa.3

fixes the documentation for numa_node_size in the numa.3 parameter and return type in man pages
(change was introduced in a7c4bc790a191d3e42b63850b409c1a72b75a4e1)

fix numa_node_size definition in manpage numa.3

---

numactl.c

The following command can trigger the bug
numactl --length 65536 --shm xxx -p0 -V > /dev/null
So reset mask to block any new access inside this loop.

numactl.c: fix use after free

---

numactl.c

numactl -C command will free cpubuff but not free cpubuff->maskp, it
will cause memleak. value mask in numactl main function will no longer
be used after argument parsing, it can free.

numactl.c: prevent memleak from cpubuff->maskp and free value mask

---

shm.c

1、The following command can trigger the bug：numactl --offset 4096 --length 65536 --file xxx -p0 --touch > /dev/null
Because  we create a shm file, we just consider shmlen, but not consider shmoffset,resulting in the mapped memory is no within the scope of the new shm file. when we access these memory will cause SIGBUS.
2、the verify_shm function memcmp nodes，when nodemask_sz is  large 64, it will output "mismatched node mask",
that's not what we expected，we expected compare nodes->mask.

fix segmentation fault with --offset and output wrong result with --verify

---

Makefile.am
libnuma.c
numa.3
numa.h
numactl.8
numactl.c
numademo.c
numaif.h
shm.c
test/prefered.c
util.c
versions.ldscript

Linux kernel 5.15 has merged a new memory policy "MPOL_PREFERRED_MANY", which allows user to specified multiple nodes as the preferred list to first allocate memory from, and till there is no available memory on those nodes, it will fallback to all other memory nodes in system.
This patchset adds the support in numactl/libnuma, and user can chose this policy by:
numactl [--preferred-many= | -P <nodes>]
And with older kernel, it will return with warning message:
"numactl: preferred-many requested without kernel support"

numactl: add support for new 'prefer-many-nodes' policy

---

Makefile.am
configure.ac

numactl currently failed to build on riscv64 from source ([Full Debian buildd log](https://buildd.debian.org/status/fetch.php?pkg=numactl&arch=riscv64&ver=2.0.14-3&stamp=1632275973&raw=0)):
```
...
/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `__atomic_fetch_and_1'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:899: migratepages] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `__atomic_fetch_and_1'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:903: migspeed] Error 1
/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `__atomic_fetch_and_1'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:907: numactl] Error 1
/usr/bin/ld: ./.libs/libnuma.so: undefined …
```

Fix build error on riscv64 by linking libatomic

---

libnuma.c

we fix it as printed, fall back to preferred and select first node of the node bitmask.
fix #136

when preferred_many is not supported, fall back to preferred will report error.

---

configure.ac

numactl unconditionally uses `__atomic_fetch_and` but some architectures (e.g. sparc) needs to link with -latomic to be able to use it. So check if -latomic is needed and update numa.pc accordingly.
This linking was made by e0de0d9e981ddb53bdeb4a4b9dc43046c9ff4ff9 but wrongly reverted by 10c277c20768be9a563f75265bcd7e73954763ad resulting in the following build failure on sparc or microblaze:
`/nvmedata/autobuild/instance-7/output-1/per-package/numactl/host/bin/../lib/gcc/sparc-buildroot-linux-uclibc/10.4.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: ./.libs/libnuma.a(libnuma.o): in function `numa_police_memory': libnuma.c:(.text+0xe28): undefined reference to `__atomic_fetch_and_1'`
Fixes:
- http://autobuild.buildroot.org/results/54b7567d804d9abff56f47cd26bae774c1e38669 …

link with -latomic if needed (again ...)

---

numactl.c

The following command can report  "numactl: Need a policy first to verify"
numactl --length=4096 --shm abc -p0 --verify
when policy uses perferred, set_policy isn't set.
Fixes: 0c844d8c("Update to support multiple nodes")
#155
'numactl --length=xxx --shm xxx -px' doesn't work
When preferred is used for shm, no value is assigned to the variable node. 
As a result, it does not take effect.
fixes: 5862e0e4("numactl: Simplify preferred selection")
#158

numactl: Fix shm verfiy for preferred policy

---

numastat.c

#147 
Because when we calculate the huge pages memory, we use the default huge page size, it maybe get worng.
After linux commit 198d1597cc5a1(fs: proc: task_mmu: show page size in /proc//numa_maps), we can obtain the correct VM page size, so we can fix it.

numastat: statistical errors occur when huge pages is used

---

numastat.c

`numastat -m` gets hugepages memory just from /sys/devices/system/node/node$/meminfo, it is not the entire hugepages memory of the system, just the default huge page.
Update the entire hugepages memory information from the /sys/devices/system/node/node$/hugepages directory.
#152

numastat: Update system hugepages memory info from sysfs/node/hugepages directory

---

numactl.c

This patch is to remove the following unused variable warning.
```
numactl.c: In function 'main':
numactl.c:425:14: warning: unused variable 'node' [-Wunused-variable]
425 |         long node=-1;
|              ^~~~
```
Since node is used nowhere inside the function so remove it.
Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

numactl.c: Remove unused variable

---

shm.c

In addition to checking that the policies are equal, also check that the nodes are equal, since the policies may be the same but apply to different nodes.
Fixes #170

numactl.c: Fix merging of neighboring pages' policies in dump_shm

---

fuzz/README.md
fuzz/fuzz_parse_str.c

Hello!
This PR adds a first fuzzer and the goal is to set up an integration of Numactl with OSS-Fuzz. OSS-Fuzz is a service run by Google for important open source projects that will continuously build and run fuzzers. There is a corresponding PR in the [OSS-Fuzz](https://github.com/google/oss-fuzz) repository (with the fuzzer included there too, but we can remove that if you're happy to accept this PR) here https://github.com/google/oss-fuzz/pull/9877
The fuzzer will be build with a set of different sanitizer (ASAN, UBSAN, MSAN) and any bugs found will be reported to maintainers listed in the corresponding `project.yaml` on the OSS-Fuzz repo (in the linked PR there is `project.yaml` with my email in for now) -- if you'd be happy to integrate then please provide a set of emails for those …

Add fuzzer for OSS-Fuzz integration

---

Makefile.am

The link command fails for wig speed with the android ndk. Also on x86_64 linux it is not needed.
reference for an "external" patch:
https://github.com/input-output-hk/haskell.nix/pull/1343/files#diff-67a1159ec1fe8bb87ad7d62668fc77d67227332e88eb5762582d24834bdab632

migspeed don't have to be linked against librt

---

libnuma.c

/* Assumes there's always a node 0, and it's online */
numa_bitmask_setbit(tmp, 0);
The node 0 is not always online if the cpuset has limited, 
so using mems allowed nodes to test new policy is more appropriate.

use mems allowed nodes to test prefer_many policy.

---

numactl.8

The execution result of `numactl --interleave=all --shm /tmp/shmkey` in manuals should be changed since we have an order among options regarding shared memory.

Fix the example usage in the numactl manual

---

memhog.c
sysfs.c

Fixes the following warnings when building on systems using the musl libc:
```
In file included from sysfs.c:4:
/usr/riscv64-unknown-linux-musl/include/sys/fcntl.h:1:2: warning: redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-W#warnings]
1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
|  ^
1 warning generated.
```
On systems using glibc this is also just a wrapper:
```
$ cat /usr/include/sys/fcntl.h
```

Include <fcntl.h> instead of <sys/fcntl.h>

---

Makefile.am
configure.ac

This reverts commit 10c277c20768be9a563f75265bcd7e73954763ad.
Whether `-latomic` needs to be linked or not depends on the used toolchain, not the architecture of the platform we build for. In my case I'm building on a riscv64 system using the LLVM toolchain, so there's not even a `-latomic` to link against. But the current logic tries to link `-latomic` anyway, resulting in a build failure.
The correct way to detect whether the used toolchain needs to link `-latomic` explicitly in order to use `__atomic_fetch_and_1` seems to be `AC_SEARCH_LIBS`.
This was
1.) introduced in e0de0d9e981d ("link with -latomic if needed")
2.) wrongly removed in commit 10c277c20768 ("Fix build error on riscv64 by linking libatomic").
3.) reinstantiated in commit 18ec3b973b72 ("link with -latomic if needed …

Revert "Fix build error on riscv64 by linking libatomic"

---

numactl.8

The --preferred and --preferred-many options have short options, but the current man page of numactl does not have the short options.
This patch fixes the man page by adding short options -p and -P.

numactl: Fix manual for --preferred and --preferred-many

---

numactl.c

This commit refines the `print_node_cpus` function to enhance output readability, especially for systems with numerous CPUs. Initially, the function itemized each CPU, leading to potentially lengthy and cluttered outputs. With this update, the function now identifies and prints contiguous CPU ranges as hyphen-separated sequences (e.g., 1-4) instead of individual lists (e.g., 1 2 3 4), streamlining the display.
Additionally, to provide a quick overview, a count of the total available CPUs is appended at the end of the output, allowing users to instantly grasp the total number without manual counting.
While the output strategy underwent these improvements, the function's core logic, error-handling, and interactions with the NUMA library remain intact, ensuring reliability and consistency …

numactl.c: Refactor print_node_cpus to display CPU ranges

---

distance.c

clang-17 warns about this set but unused variable:
```
distance.c:34:6: warning: variable 'numnodes' set but not used [-Wunused-but-set-variable]
34 |         int numnodes = 0;
|             ^
1 warning generated.
```
and it's indeed just used to count the nodes in the for loop but then it's never used

Draft: distance: Remove unused variable (NFC)

---

util.c

When using the complain() function to output stderr, the newline character doesn't take effect.
```shell
[luochenglcs@TENCENT64 numactl]$ numactl --shm xxx --touch > /dev/null
numactl: need a --length to create a sysv shared memory segment[luochenglcs@TENCENT64 numactl]$
```
After fixed:
```shell
[luochenglcs@TENCENT64 numactl]$ numactl --shm xxx --touch > /dev/null
numactl: need a --length to create a sysv shared memory segment
[luochenglcs@TENCENT64 numactl]$ 
```

fix complain() fuction print newline

---

libnuma.c

Fix some unexpected output

---

libnuma.c
numa.3
numa.h
numaif.h
syscall.c
versions.ldscript

add numa_set_mempolicy_home_node to set home_node for mbind or preferred_many policy.
link: https://lore.kernel.org/all/20211202123810.267175-3-aneesh.kumar@linux.ibm.com/T/#u

libnuma: add numa_set_mempolicy_home_node API

---

memhog.8
migratepages.8
migspeed.8
numactl.8

lintian in Debian started complaining
W: numactl: groff-message an.tmac:<standard input>:110: warning: tbl
preprocessor failed, or it or soelim was not run; table(s) likely not
rendered (TE macro called with TW register undefined)
for these man pages.  I would claim to barely understand the ancient ruins that are man page header macros, but from what I can divine from [1] what we're looking at here is an incorrect inclusion of the "tbl" preprocessor, which should be '\" t not .\" t.
This silences the warnings, at least.
[1] https://manpages.debian.org/bookworm/man-db/man.1.en.html#DEFAULTS

man pages: fix table include preprocessor

---

numactl.c
numademo.c

Fix warning:
numactl.c:189: leaked_storage: Variable ""preferred"" going out of scope leaks the storage it points to.                                       #  187|           printmask(""membind"", membind);
And
numademo.c:153: var_decl: Declaring variable ""end"" without initializer.

Fix some warning thrown by static checking tools

---

numastat.c

Hash the tokens during the first node processing.   This eliminates the need for hard-coded tables, and keeps the program up-to-date.

numastat: eliminate hard-coded tables

---

libnuma.c

This prevents buffer corrpution which manifests as firefox failing to play videos with mimalloc in hardened mode (as the get_mempolicy will corrupt the metadata).
The documentation for get_mempolicy specifies the following:
```
unsigned long nodemask[(.maxnode + ULONG_WIDTH - 1)
/ ULONG_WIDTH]
```
where maxnode is the following argument. Since we are calling get_mempolicy with `nodemask_sz + 1`, that means the size will be `(nodemask_sz + 1 + ULONG_WIDTH - 1) / ULONG_WIDTH)` i.e. `(nodemask_sz + ULONG_WIDTH) / ULONG_WIDTH` or `nodemask_sz / ULONG_WIDTH + 1`.
Since `ULONG_WIDTH` is `sizeof ulong * 8`, and the nodemask is an array of ulong, that means the allocation size should be:
```
sizeof ulong * (nodemask_sz / (sizeof ulong * 8) + 1)
```
which is equal to:
```
sizeof ulong + …
```

libnuma: fix nodemask allocation size for get_mempolicy

---

libnuma.c

Make numa_available respect EPERM
In the Docker environment, usage of `get_mempolicy` is restricted by seccomp security profiles: https://docs.docker.com/engine/security/seccomp/ (unless `CAP_SYS_NICE` is set).
But `numa_available` used to ignore EPERM and return 'true', i.e., available. This led to further code attempting other API calls, which resulted in "operation not permitted" errors printed to stderr.
See details in:
https://github.com/ClickHouse/ClickHouse/issues/68747#issuecomment-2426210768

Make numa_available respect EPERM

---

libnuma.c

Example report
```
==352==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x5601962f55a3 in numa_get_membind_v2 build_docker/./contrib/numactl/libnuma.c:1259:6
#1 0x5601951b371c in DB::getNumaNodesTotalMemory() build_docker/./base/base/Numa.cpp:18:26
#2 0x56017338880d in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/./programs/server/Server.cpp:905:34
#3 0x5601954a2d7e in Poco::Util::Application::run() build_docker/./base/poco/Util/src/Application.cpp:315:8
#4 0x560173379f8a in DB::Server::run() build_docker/./programs/server/Server.cpp:533:25
#5 0x5601954ea05f in …
```

Fix some uninitialized variables reported by memory sanitizer

---

libnuma.c
numa.3
numa.h
versions.ldscript

This PR adds weighted-interleaved allocations to libnuma APIs and a few cleanups for numa.3 man page. The description copied from the last commit:
Currently libnuma only supports per-process weighted interleaving policy. Introduce libnuma APIs to enforce specific memory mappings to be distributed in the weighted interleave mode.
To align with the existing support for the traditional interleaving, introduce three APIs, one that interleaves allocations on NUMA nodes specified in the nodemask, another that interleaves allocations on all NUMA nodes, and the other that updates the memory policy of an existing mapping:
* numa_alloc_weighted_interleaved_subset(size, bitmask)
* numa_alloc_weighted_interleaved(size)
* numa_weighted_interleave_memory(start, size, nodemask)
Close #237

libnuma: support weighted-interleaved allocations

---

numademo.c
util.c

This PR adds tests for the following weighted-interleaved allocations APIs in numademo.c as mentioned in [1]:
```
numa_alloc_weighted_interleaved_subset(size, bitmask)
numa_alloc_weighted_interleaved(size)
```
It aligns with the tests for existing NUMA allocation APIs.
In my understand, regression test codes in numactl are `numademo.c` and `test/regress`, is that correct?
`numademo.c` allocates memory with various numa_alloc APIs and measures allocation throughput. I'm wondering if it is sufficient to determine if a regression has occured.
I'm not familiar with regression testing, so I'm curious about how it's conducted.
[1] https://github.com/numactl/numactl/pull/238#issuecomment-2541867063

numademo: Add tests for weighted-interleaved allocations

---

Makefile.am
libnuma.c
numa.3
numa.h
numactl.c
util.c
versions.ldscript

The main motivation of this PR is to improve the output of `numactl --show` command for MPOL_WEIGHTED_INTERLEAVE  policy (before/after at the end of this PR). But it also includes some improvements listed below.
This PR does:
- Introduce numa_get_weighted_interleave_mask() API.
- Document both numa_{get,set}_weighted_interleave_mask() APIs.
- Fixes memory leaks of numactl --show option (in `show()` function).
- Improves the output of `numactl --show` option.
[Cc @gmprice who introduced weighted interleaving support in libnuma]
Currently, numactl --show does not properly support MPOL_WEIGHTED_INTERLEAVE:
```bash
$ ./numactl --weighted-interleave=0,2,3 ./numactl --show
policy: [6]
preferred node: physcpubind: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 …
```

Better support for MPOL_WEIGHTED_INTERLEAVE

---

libnuma.c
numa.3
numa.h
versions.ldscript

After commit 87c6834 ( libnuma: Convert preferred node into a mask), numa_preferred() returns -1 if no suitable node is found. Before that, it returns 0.
Some users still expect the old behavior, and they use 0 as an index to an array. Let's clarify here that this is incorrect.

Introduce numa_preferred_err() API

---

numastat.c

We see the device path hardcoded with node0.
it presumes node0 always exist, and it just counts the number of rows of information in the file for later uses where it does process the nodes as expected.
Before patch - 
#numastat
cannot open /sys/devices/system/node/node0/numastat: No such file or directory
After patch 
#numastat
node1
numa_hit                 2656761
numa_miss                      0
numa_foreign                   0
interleave_hit               556
local_node               2656761
other_node                     0

numastat command fails on LPAR which is not having node0

---

distance.c
libnuma.c
memhog.c
migspeed.c
numademo.c
shm.c
syscall.c
sysfs.c
test/tbitmap.c

When building with `clang` with `-std=c99` I encountered some errors in which `_GNU_SOURCE` was not declared in all files that needed it. In addition, normally one only needs to declare `_GNU_SOURCE`, not assign it a value; this caused some problems when I initially tried to pass `-D_GNU_SOURCE` through via the compiler.

Add `_GNU_SOURCE` to additional files 

---

libnuma.c

so use strong variation with
```
__atomic_compare_exchange_n(&node_cpu_mask_v2, &null_ncm,
new_ncm, 0,
__ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)
```

__atomic_compare_exchange_n may fail and cause a segmentation fault
